# Generated by Django 6.0.4 on 2026-08-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_published_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('image_url', models.URLField(blank=True, max_length=600, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('pilgrimage', 'Pilgrimage & Spiritual'), ('nature', 'Nature & Wildlife'), ('heritage', 'Heritage & Culture'), ('adventure', 'Adventure & Outdoors'), ('urban', 'Cities & Lifestyle'), ('general', 'General')], db_index=True, default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide / Material icon name', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_type'], name='categories__categor_51118c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['name'], name='categories__name_ce3d61_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['slug'], name='categories__slug_47375c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['published'], name='categories__publish_e1284e_idx'),
        ),
    ]
