# Generated by Django 6.0.4 on 2026-08-13 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_published_alter_city_banner_image_and_more'),
        ('destinations', '0003_alter_attraction_options_and_more'),
        ('states', '0002_state_image_state_latitude_state_longitude_and_more'),
        ('travel_guides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('photo', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField()),
                ('languages_spoken', models.CharField(default='English, Hindi, Telugu', max_length=200)),
                ('experience_years', models.IntegerField(default=5)),
                ('rating', models.DecimalField(decimal_places=2, default=4.85, max_digits=3)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=1500.0, max_digits=8)),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=30)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_guides', to='cities.city')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_guides', to='destinations.destination')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_guides', to='states.state')),
            ],
            options={
                'ordering': ['-rating', '-experience_years'],
            },
        ),
    ]
