# Generated by Django 6.0.4 on 2026-08-18 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_published_alter_city_banner_image_and_more'),
        ('destinations', '0004_herodestination'),
        ('states', '0002_state_image_state_latitude_state_longitude_and_more'),
        ('travel_guides', '0002_localguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('category', models.CharField(choices=[('hidden', 'Hidden India'), ('culture', 'Culture & Traditions'), ('food', 'Food Stories'), ('heritage', 'Royal & Heritage'), ('spiritual', 'Sacred & Spiritual'), ('adventure', 'Adventure & Exploration'), ('wildlife', 'Wild India'), ('nature', 'Nature & Landscapes'), ('coastal', 'Coastal India'), ('mountain', 'Mountain India'), ('festival', 'Festival Stories')], db_index=True, default='hidden', max_length=50)),
                ('category_label', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(default='India', max_length=150)),
                ('short_description', models.TextField(help_text='Engaging 1-2 sentence overview for cards')),
                ('content', models.TextField()),
                ('cover_image', models.URLField(max_length=600)),
                ('author', models.CharField(default='Dekho Bharat Editorial', max_length=120)),
                ('author_role', models.CharField(blank=True, default='Travel Chronicler', max_length=120, null=True)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='cities.city')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='destinations.destination')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='states.state')),
            ],
            options={
                'ordering': ['display_order', '-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['category'], name='travel_guid_categor_d48e4a_idx'), models.Index(fields=['is_featured'], name='travel_guid_is_feat_72da1c_idx'), models.Index(fields=['is_active'], name='travel_guid_is_acti_caadd6_idx'), models.Index(fields=['slug'], name='travel_guid_slug_fe619a_idx')],
            },
        ),
    ]
