import csv

rows = [
    {
        "name": "Belum Caves",
        "slug": "belum-caves-andhra",
        "region": "south-india",
        "state": "Andhra Pradesh",
        "district": "Kurnool",
        "city": "Belum",
        "short_description": "The second longest and largest natural cave system in the Indian subcontinent.",
        "full_description": "Belum Caves feature stalactite and stalagmite formations with subterranean water passages.",
        "history": "Formed over millions of years by the perennial flow of underground river Chitravati.",
        "historical_significance": "Ancient Buddhist and Jain relics were discovered inside these limestone passages.",
        "cultural_significance": "Archaeological and spiritual haven for Jain monks in ancient centuries.",
        "religious_significance": "Sacred meditation chambers used by Buddhist monks.",
        "latitude": "15.1017",
        "longitude": "78.1121",
        "best_time_to_visit": "October to March",
        "recommended_duration": "1 Day",
        "estimated_budget": "budget",
        "categories": "nature,adventure",
        "activities": "hiking,photography",
        "tags": "weekend-trip,family-friendly",
        "nearest_airport": "Kadapa Airport (CDP)",
        "nearest_railway_station": "Tadipatri Railway Station",
        "nearest_bus_station": "Belum Bus Station",
        "how_to_reach": "Direct road access via NH 44 and SH 57 from Kurnool.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    },
    {
        "name": "Ramappa Temple",
        "slug": "ramappa-temple-telangana",
        "region": "south-india",
        "state": "Telangana",
        "district": "Mulugu",
        "city": "Palampet",
        "short_description": "13th-century Kakatiya masterpiece and UNESCO World Heritage Site.",
        "full_description": "Revered for its lightweight floating bricks and intricately carved black basalt pillars.",
        "history": "Constructed in 1213 CE under Kakatiya ruler Ganapati Deva by master sculptor Ramappa.",
        "historical_significance": "Celebrated as the only temple in India named after its architect Ramappa.",
        "cultural_significance": "Epitome of classical Kakatiya dance sculptures and temple architecture.",
        "religious_significance": "Dedicated to Lord Ramalingeswara Swamy.",
        "latitude": "18.2602",
        "longitude": "79.9431",
        "best_time_to_visit": "October to March",
        "recommended_duration": "1 Day",
        "estimated_budget": "budget",
        "categories": "temples,heritage",
        "activities": "heritage-walk,photography",
        "tags": "unesco,ancient",
        "nearest_airport": "Hyderabad Rajiv Gandhi International (HYD)",
        "nearest_railway_station": "Warangal Railway Station",
        "nearest_bus_station": "Mulugu Bus Station",
        "how_to_reach": "Well-connected by Telangana state highways via Warangal.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    },
    {
        "name": "Mahabalipuram Shore Temple",
        "slug": "shore-temple-tamil-nadu",
        "region": "south-india",
        "state": "Tamil Nadu",
        "district": "Chengalpattu",
        "city": "Mahabalipuram",
        "short_description": "7th-century coastal monolithic rock-cut UNESCO World Heritage marvel.",
        "full_description": "Built overlooking the Bay of Bengal under the Pallava dynasty featuring Pancha Rathas and Arjuna's Penance.",
        "history": "Constructed in the 700s CE by Pallava King Narasimhavarman II.",
        "historical_significance": "Ancient international maritime trading port connecting India with Southeast Asia.",
        "cultural_significance": "Signature Dravidian Pallava rock-cut structural temple architecture.",
        "religious_significance": "Revered shrines dedicated to Lord Shiva and Lord Vishnu.",
        "latitude": "12.6167",
        "longitude": "80.1983",
        "best_time_to_visit": "November to February",
        "recommended_duration": "1-2 Days",
        "estimated_budget": "mid_range",
        "categories": "heritage,beaches",
        "activities": "heritage-walk,photography",
        "tags": "unesco,coastal",
        "nearest_airport": "Chennai International Airport (MAA)",
        "nearest_railway_station": "Chengalpattu Railway Station",
        "nearest_bus_station": "Mahabalipuram Bus Stand",
        "how_to_reach": "Scenic drive via East Coast Road (ECR) from Chennai.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    },
    {
        "name": "Jog Falls",
        "slug": "jog-falls-karnataka",
        "region": "south-india",
        "state": "Karnataka",
        "district": "Shivamogga",
        "city": "Sagara",
        "short_description": "India's second highest plunge waterfall formed by the Sharavathi River.",
        "full_description": "Cascades dramatically down 253 meters in four distinct torrents known as Raja, Rani, Roarer, and Rocket.",
        "history": "Documented by early explorers and immortalized in Kannada literature and coastal folklore.",
        "historical_significance": "Natural hydro-energy landmark of Karnataka powering Mahatma Gandhi hydroelectric project.",
        "cultural_significance": "Awe-inspiring nature wonder celebrating the power of the Western Ghats monsoon.",
        "religious_significance": "Sacred natural sanctuary nestled in lush evergreen forests of Sahyadri.",
        "latitude": "14.2285",
        "longitude": "74.8105",
        "best_time_to_visit": "July to December",
        "recommended_duration": "1-2 Days",
        "estimated_budget": "budget",
        "categories": "waterfalls,nature",
        "activities": "photography,hiking",
        "tags": "monsoon,nature",
        "nearest_airport": "Mangalore International Airport (IXE)",
        "nearest_railway_station": "Talguppa Railway Station",
        "nearest_bus_station": "Jog Falls Bus Stand",
        "how_to_reach": "Connected via NH 206 from Shivamogga and Sagara.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    },
    {
        "name": "Ajanta and Ellora Caves",
        "slug": "ajanta-ellora-caves-maharashtra",
        "region": "west-india",
        "state": "Maharashtra",
        "district": "Aurangabad",
        "city": "Chhatrapati Sambhajinagar",
        "short_description": "UNESCO World Heritage rock-cut cave monuments spanning 2nd century BCE to 10th century CE.",
        "full_description": "34 rock-cut monolithic caves at Ellora including the world's largest rock monolithic Kailash Temple.",
        "history": "Carved by Buddhist, Hindu, and Jain artisans across Rashtrakuta and Yadava dynasties.",
        "historical_significance": "Monolithic engineering zenith where an entire mountain temple was carved from top to bottom.",
        "cultural_significance": "Unmatched ancient Indian fresco murals and rock sculpture traditions.",
        "religious_significance": "Sacred cave shrines honoring Shiva, Buddha, and Tirthankaras.",
        "latitude": "20.0268",
        "longitude": "75.1780",
        "best_time_to_visit": "October to March",
        "recommended_duration": "2-3 Days",
        "estimated_budget": "mid_range",
        "categories": "heritage,monuments",
        "activities": "heritage-walk,photography",
        "tags": "unesco,ancient",
        "nearest_airport": "Aurangabad Airport (IXU)",
        "nearest_railway_station": "Aurangabad Railway Station",
        "nearest_bus_station": "Ellora Bus Stand",
        "how_to_reach": "Regular buses and tourist taxis available from Aurangabad.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    },
    {
        "name": "Pichola Lake & City Palace",
        "slug": "lake-pichola-udaipur",
        "region": "north-india",
        "state": "Rajasthan",
        "district": "Udaipur",
        "city": "Udaipur",
        "short_description": "The Venice of the East featuring majestic Rajput palaces set around turquoise lake waters.",
        "full_description": "City Palace complex built over 400 years on the eastern banks of Lake Pichola.",
        "history": "Founded in 1559 CE by Maharana Udai Singh II after shifting the Mewar capital from Chittorgarh.",
        "historical_significance": "Defiant capital of the Sisodia Rajput warrior dynasty that resisted foreign conquest.",
        "cultural_significance": "Rajput architectural marvel blending granite, marble, and colorful glass mosaics.",
        "religious_significance": "Home to the sacred Jagdish Temple dedicated to Lord Vishnu.",
        "latitude": "24.5764",
        "longitude": "73.6835",
        "best_time_to_visit": "October to March",
        "recommended_duration": "2-3 Days",
        "estimated_budget": "luxury",
        "categories": "heritage,culture",
        "activities": "boating,photography",
        "tags": "royal,romantic",
        "nearest_airport": "Maharana Pratap Airport Udaipur (UDR)",
        "nearest_railway_station": "Udaipur City Railway Station",
        "nearest_bus_station": "Udaipur Central Bus Stand",
        "how_to_reach": "Well-connected via NH 48 with direct luxury buses and trains.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    },
    {
        "name": "Valley of Flowers",
        "slug": "valley-of-flowers-uttarakhand",
        "region": "north-india",
        "state": "Uttarakhand",
        "district": "Chamoli",
        "city": "Govindghat",
        "short_description": "UNESCO World Heritage high-altitude alpine meadow carpeted with hundreds of endemic Himalayan flowers.",
        "full_description": "Sprawls across the transition zone between Zanskar and Great Himalaya ranges alongside Pushpawati River.",
        "history": "Discovered in 1931 by British mountaineer Frank S. Smythe during a Kamet expedition.",
        "historical_significance": "Celebrated botanist and trekker paradise surrounded by towering snow-capped peaks.",
        "cultural_significance": "Deeply revered in local folklore as the mythical Gandhamardan mountain of Sanjeevani herb.",
        "religious_significance": "Gateway to the sacred high-altitude Hemkund Sahib Sikh pilgrimage shrine.",
        "latitude": "30.7280",
        "longitude": "79.6053",
        "best_time_to_visit": "July to September",
        "recommended_duration": "3-4 Days",
        "estimated_budget": "mid_range",
        "categories": "mountains,nature",
        "activities": "trekking,photography",
        "tags": "unesco,adventure",
        "nearest_airport": "Jolly Grant Airport Dehradun (DED)",
        "nearest_railway_station": "Rishikesh Railway Station",
        "nearest_bus_station": "Govindghat Bus Stand",
        "how_to_reach": "Trek begins from Govindghat via Ghangaria along the holy Alaknanda corridor.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    },
    {
        "name": "Spiti Valley",
        "slug": "spiti-valley-himachal",
        "region": "north-india",
        "state": "Himachal Pradesh",
        "district": "Lahaul and Spiti",
        "city": "Kaza",
        "short_description": "Cold mountain desert valley nestled high in the Himalayas at 3,800m altitude.",
        "full_description": "Famous for ancient 1,000-year-old Key Monastery, Chandratal lake, and fossil-rich villages.",
        "history": "Historically an autonomous kingdom linked spiritually and culturally with Western Tibet.",
        "historical_significance": "Pristine epicenter of Tibetan Gelugpa Buddhist learning and asceticism.",
        "cultural_significance": "Centuries-old mud-and-timber fortified monasteries clinging to sheer cliffs.",
        "religious_significance": "Sacred home to the thousand-year-old Key Gompa and Tabo Monastery.",
        "latitude": "32.2276",
        "longitude": "78.0710",
        "best_time_to_visit": "May to October",
        "recommended_duration": "5-7 Days",
        "estimated_budget": "mid_range",
        "categories": "mountains,adventure",
        "activities": "camping,photography",
        "tags": "adventure,snow",
        "nearest_airport": "Bhuntar Airport Kullu (KUU)",
        "nearest_railway_station": "Shimla Railway Station",
        "nearest_bus_station": "Kaza Bus Depot",
        "how_to_reach": "Approached via Manali-Atal Tunnel route or Shimla-Kinnaur valley route.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    },
    {
        "name": "Gulmarg",
        "slug": "gulmarg-kashmir",
        "region": "north-india",
        "state": "Jammu and Kashmir",
        "district": "Baramulla",
        "city": "Gulmarg",
        "short_description": "The Meadow of Flowers and premier Himalayan winter skiing and gondola haven.",
        "full_description": "Features the world's second highest operating cable car reaching 3,980m.",
        "history": "Beloved summer retreat of Mughal Emperor Jahangir and 19th-century British officers.",
        "historical_significance": "Global destination for powder snow heli-skiing and alpine winter sports.",
        "cultural_significance": "Colonial pine chalets, historic St. Mary's stone church, and wooden lodges.",
        "religious_significance": "Home to the historic Maharani Temple built in 1915 by Queen Mohini Bai Sisodia.",
        "latitude": "34.0484",
        "longitude": "74.3805",
        "best_time_to_visit": "Year-round",
        "recommended_duration": "3 Days",
        "estimated_budget": "luxury",
        "categories": "mountains,adventure",
        "activities": "skiing,photography",
        "tags": "snow,romantic",
        "nearest_airport": "Srinagar International Airport (SXR)",
        "nearest_railway_station": "Jammu Tawi Railway Station",
        "nearest_bus_station": "Gulmarg Tangmarg Bus Stand",
        "how_to_reach": "Scenic 50 km drive from Srinagar via Tangmarg.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    },
    {
        "name": "Living Root Bridges",
        "slug": "living-root-bridges-meghalaya",
        "region": "northeast-india",
        "state": "Meghalaya",
        "district": "East Khasi Hills",
        "city": "Nongriat",
        "short_description": "Bio-engineering wonder grown over centuries by indigenous Khasi tribes from Indian rubber tree roots.",
        "full_description": "Features the famous Double Decker Living Root Bridge spanning across crystal rainforest streams.",
        "history": "Centuries-old indigenous bio-engineering passed down across generations.",
        "historical_significance": "Living ecological heritage exemplifying harmonious coexistence between humans and nature.",
        "cultural_significance": "Living architecture trained over river torrents across 15 to 30 years of growth.",
        "religious_significance": "Sacred groves and ancestral forests protected under traditional Khasi customs.",
        "latitude": "25.2500",
        "longitude": "91.6800",
        "best_time_to_visit": "October to April",
        "recommended_duration": "2 Days",
        "estimated_budget": "budget",
        "categories": "nature,adventure",
        "activities": "trekking,hiking",
        "tags": "nature,monsoon",
        "nearest_airport": "Shillong Airport (SHL)",
        "nearest_railway_station": "Guwahati Railway Station",
        "nearest_bus_station": "Cherrapunji Sohra Stand",
        "how_to_reach": "Scenic trek descending 3,500 stone steps from Tyrna village near Cherrapunji.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    },
    {
        "name": "Sun Temple Konark",
        "slug": "konark-sun-temple-odisha",
        "region": "east-india",
        "state": "Odisha",
        "district": "Puri",
        "city": "Konark",
        "short_description": "13th-century architectural marvel designed as a monumental 24-wheeled chariot of Surya.",
        "full_description": "UNESCO World Heritage Site renowned for intricate stone wheels acting as sundials.",
        "history": "Built around 1250 CE by King Narasimhadeva I of the Eastern Ganga Dynasty.",
        "historical_significance": "Monumental ocean landmark known as the Black Pagoda by European sailors.",
        "cultural_significance": "Kalinga style sandstone architecture carved with celestial dancers and mythological lore.",
        "religious_significance": "Revered sanctuary dedicated to Surya the Sun God.",
        "latitude": "19.8876",
        "longitude": "86.0945",
        "best_time_to_visit": "October to March",
        "recommended_duration": "1-2 Days",
        "estimated_budget": "mid_range",
        "categories": "temples,heritage",
        "activities": "heritage-walk,photography",
        "tags": "unesco,ancient",
        "nearest_airport": "Biju Patnaik Airport Bhubaneswar (BBI)",
        "nearest_railway_station": "Puri Railway Station",
        "nearest_bus_station": "Konark Bus Stand",
        "how_to_reach": "Direct 35 km Marine Drive highway from Puri.",
        "featured": "True",
        "verified": "True",
        "published": "True"
    }
]

with open('test_all_india_destinations.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    writer.writerows(rows)

print("Generated test_all_india_destinations.csv with", len(rows), "properly formatted destinations.")
