# Generated by Django 6.0.4 on 2026-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0004_herodestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='experiences/images/')),
                ('cover_video', models.FileField(blank=True, help_text='Cinematic video for this experience', null=True, upload_to='experiences/videos/')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_destinations', models.ManyToManyField(blank=True, related_name='experiences', to='destinations.destination')),
            ],
            options={
                'verbose_name_plural': 'Experiences',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='experiences_name_20bb7d_idx'), models.Index(fields=['slug'], name='experiences_slug_bf245c_idx'), models.Index(fields=['is_active'], name='experiences_is_acti_0da7bb_idx'), models.Index(fields=['display_order'], name='experiences_display_8672b1_idx')],
            },
        ),
    ]
