# Generated by Django 6.0.4 on 2026-08-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cuisine_type', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('avg_cost_for_two', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, default=4.2, max_digits=3)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='cities.city')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='destinations.destination')),
            ],
        ),
    ]
