# Generated by Django 6.0.4 on 2026-08-13 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_initial'),
        ('itineraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='itineraryplace',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_appearances', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='itineraryplace',
            name='itinerary_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='itineraries.itineraryday'),
        ),
    ]
