# Generated by Django 6.0.4 on 2026-08-13 16:51

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('states', '0002_state_image_state_latitude_state_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='banner_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.utils.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.utils.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='cities_city_name_a4d1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['slug'], name='cities_city_slug_2e6a48_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['published'], name='cities_city_publish_38b9fd_idx'),
        ),
    ]
