# Generated by Django 6.0.4 on 2026-08-19 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_published_alter_city_banner_image_and_more'),
        ('states', '0003_state_region_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='states.district'),
        ),
    ]
