# Generated by Django 6.0.4 on 2026-08-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_union_territory', models.BooleanField(default=False)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_image', models.URLField(blank=True, max_length=500, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200, null=True)),
                ('culture_info', models.TextField(blank=True, null=True)),
                ('food_info', models.TextField(blank=True, null=True)),
                ('festival_info', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
