# Generated by Django 6.0.4 on 2026-08-13 16:51

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='states/'),
        ),
        migrations.AddField(
            model_name='state',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.utils.validate_latitude]),
        ),
        migrations.AddField(
            model_name='state',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.utils.validate_longitude]),
        ),
        migrations.AddField(
            model_name='state',
            name='published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='banner_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name'], name='states_stat_name_be14c2_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['slug'], name='states_stat_slug_a33f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['published'], name='states_stat_publish_02b0f0_idx'),
        ),
    ]
