# Generated by Django 6.0.4 on 2026-08-19 10:51

import apps.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('states', '0002_state_image_state_latitude_state_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='regions.region'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('headquarters', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.utils.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.utils.validate_longitude])),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='states.state')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='states_dist_name_f985d5_idx'), models.Index(fields=['slug'], name='states_dist_slug_6e2562_idx'), models.Index(fields=['state'], name='states_dist_state_i_d0388e_idx')],
                'unique_together': {('name', 'state')},
            },
        ),
    ]
