# Generated by Django 6.0.4 on 2026-08-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('desktop_video', models.URLField(blank=True, help_text='URL to desktop cinematic video', max_length=500, null=True)),
                ('mobile_video', models.URLField(blank=True, help_text='URL to mobile cinematic video', max_length=500, null=True)),
                ('poster_image', models.URLField(blank=True, help_text='URL to poster image fallback', max_length=500, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which region appears in the UI')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['display_order'],
            },
        ),
    ]
