# Generated by Django 6.0.4 on 2026-08-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('cities', '0001_initial'),
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('history', models.TextField(blank=True, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200, null=True)),
                ('opening_time', models.CharField(blank=True, default='06:00 AM', max_length=100, null=True)),
                ('closing_time', models.CharField(blank=True, default='06:00 PM', max_length=100, null=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('recommended_duration', models.CharField(blank=True, default='2-3 Hours', max_length=100, null=True)),
                ('how_to_reach', models.TextField(blank=True, null=True)),
                ('airport_information', models.TextField(blank=True, null=True)),
                ('railway_information', models.TextField(blank=True, null=True)),
                ('bus_information', models.TextField(blank=True, null=True)),
                ('local_transport', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('is_hidden_gem', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('budget_level', models.CharField(choices=[('low', 'Budget / Low'), ('medium', 'Moderate / Medium'), ('high', 'Luxury / High')], default='medium', max_length=20)),
                ('travel_style', models.CharField(choices=[('family', 'Family'), ('couple', 'Couple / Romantic'), ('solo', 'Solo Explorer'), ('adventure', 'Adventure'), ('spiritual', 'Spiritual'), ('nature', 'Nature'), ('historical', 'Historical'), ('cultural', 'Cultural'), ('beach', 'Beach'), ('wildlife', 'Wildlife')], default='family', max_length=20)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('main_image', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='categories.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='cities.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='states.state')),
            ],
            options={
                'ordering': ['-featured', '-trending', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='destinations.destination')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
