# Generated by Django 6.0.4 on 2026-08-13 16:51

import apps.utils
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_published_alter_category_image_and_more'),
        ('cities', '0002_city_published_alter_city_banner_image_and_more'),
        ('destinations', '0002_initial'),
        ('states', '0002_state_image_state_latitude_state_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='destinationimage',
            options={'ordering': ['display_order', '-is_primary', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='destinationvideo',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='traveltip',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.RenameField(
            model_name='traveltip',
            old_name='tip',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='category',
        ),
        migrations.RemoveField(
            model_name='destinationimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='closing_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.utils.validate_latitude]),
        ),
        migrations.AddField(
            model_name='attraction',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.utils.validate_longitude]),
        ),
        migrations.AddField(
            model_name='attraction',
            name='opening_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='attraction',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='attraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='categories.category'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='image',
            field=models.ImageField(default='destinations/images/default.jpg', upload_to='destinations/images/', validators=[apps.utils.validate_image_file]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/videos/'),
        ),
        migrations.AddField(
            model_name='traveltip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveltip',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traveltip',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='traveltip',
            name='title',
            field=models.CharField(default='General Tip', max_length=200),
        ),
        migrations.AddField(
            model_name='traveltip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attractions/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.utils.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.utils.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='short_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='destination',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['name'], name='destination_name_96ccc3_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['slug'], name='destination_slug_528bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['published'], name='destination_publish_470086_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['featured'], name='destination_feature_05c406_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['trending'], name='destination_trendin_854c84_idx'),
        ),
    ]
