# Generated by Django 6.0.4 on 2026-08-15 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_attraction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(help_text='Fallback name if not linked to a Destination', max_length=200)),
                ('region', models.CharField(choices=[('SOUTH', 'South India'), ('NORTH', 'North India'), ('WEST', 'West India'), ('EAST', 'East India'), ('CENTRAL', 'Central India'), ('NORTHEAST', 'Northeast India')], db_index=True, default='SOUTH', max_length=20)),
                ('state_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('youtube_video_id', models.CharField(blank=True, help_text='YouTube ID (preferred)', max_length=50, null=True)),
                ('desktop_video', models.FileField(blank=True, help_text='Raw MP4 if YouTube is not used', null=True, upload_to='hero_videos/')),
                ('mobile_video', models.FileField(blank=True, null=True, upload_to='hero_videos/mobile/')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='hero_posters/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('transition_type', models.CharField(choices=[('CROSSFADE', 'Cinematic Crossfade'), ('ZOOM', '3D Zoom'), ('SLIDE', 'Depth Slide'), ('SWEEP', 'Light Sweep')], default='CROSSFADE', max_length=20)),
                ('display_duration', models.PositiveIntegerField(default=10, help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_features', to='destinations.destination')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
