# Generated by Django 6.0.4 on 2026-08-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_published_alter_category_image_and_more'),
        ('cities', '0002_city_published_alter_city_banner_image_and_more'),
        ('destinations', '0004_herodestination'),
        ('states', '0002_state_image_state_latitude_state_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['display_order', '-featured', '-trending', 'name']},
        ),
        migrations.AddField(
            model_name='destination',
            name='culture_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='data_completeness_score',
            field=models.PositiveIntegerField(default=92, help_text='Score out of 100'),
        ),
        migrations.AddField(
            model_name='destination',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='famous_for',
            field=models.CharField(blank=True, help_text='Highlights & USP', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='last_verified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='nearest_airport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='nearest_bus_station',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='nearest_railway',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='pilgrimage_collection',
            field=models.CharField(choices=[('jyotirlinga', '12 Jyotirlingas'), ('char_dham', 'Maha Char Dham'), ('chota_char_dham', 'Chota Char Dham (Uttarakhand)'), ('shakti_peetha', '51 Shakti Peethas'), ('buddhist_circuit', 'Buddhist Heritage Circuit'), ('sikh_pilgrimage', 'Sikh Historical Gurudwaras'), ('jain_tirth', 'Jain Tirthankar Sites'), ('panch_kedar', 'Panch Kedar'), ('panch_prayag', 'Panch Prayag'), ('divya_desam', '108 Divya Desams'), ('none', 'General Destination')], db_index=True, default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='destination',
            name='popularity_score',
            field=models.PositiveIntegerField(default=85, help_text='Score out of 100'),
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.CharField(choices=[('south-india', 'South India'), ('north-india', 'North India'), ('west-india', 'West India'), ('east-india', 'East India'), ('central-india', 'Central India'), ('northeast-india', 'Northeast India')], db_index=True, default='south-india', max_length=40),
        ),
        migrations.AddField(
            model_name='destination',
            name='safety_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='source_name',
            field=models.CharField(blank=True, default='Ministry of Tourism, Govt of India', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='spiritual_tradition',
            field=models.CharField(blank=True, help_text='e.g. Shaivism, Vaishnavism, Shaktism, Buddhism, Jainism, Sikhism', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='temple_architecture',
            field=models.CharField(blank=True, help_text='e.g. Dravidian, Nagara, Kalinga, Cave Architecture, Hoysala', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='temple_deity',
            field=models.CharField(blank=True, help_text='e.g. Lord Shiva, Lord Venkateswara, Goddess Durga', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='things_to_do',
            field=models.TextField(blank=True, help_text='List of top activities', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_tips_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='verification_status',
            field=models.CharField(choices=[('verified', '100% Verified'), ('needs_verification', 'Needs Verification'), ('incomplete', 'Incomplete Data'), ('outdated', 'Outdated Info')], db_index=True, default='verified', max_length=30),
        ),
        migrations.AddField(
            model_name='destination',
            name='weather_info',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=4.8, max_digits=3),
        ),
        migrations.AlterField(
            model_name='destination',
            name='total_reviews',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='herodestination',
            name='desktop_video',
            field=models.FileField(blank=True, null=True, upload_to='hero_videos/'),
        ),
        migrations.AlterField(
            model_name='herodestination',
            name='display_duration',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='herodestination',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['region'], name='destination_region_ebb36c_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['district'], name='destination_distric_a2708a_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['pilgrimage_collection'], name='destination_pilgrim_3eb447_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['verification_status'], name='destination_verific_9ef932_idx'),
        ),
    ]
