# Generated by Django 6.0.4 on 2026-08-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_published_alter_category_image_and_more'),
        ('cities', '0002_city_published_alter_city_banner_image_and_more'),
        ('destinations', '0005_alter_destination_options_and_more'),
        ('states', '0002_state_image_state_latitude_state_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='ideal_season',
            field=models.CharField(choices=[('all_year', 'All Year Round'), ('monsoon', 'Monsoon (Jul-Sep)'), ('winter', 'Winter (Oct-Feb)'), ('summer', 'Summer (Mar-Jun)')], db_index=True, default='all_year', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='suitable_for_tags',
            field=models.CharField(default='beginners, families, weekend', help_text='e.g. beginners, families, couples, photography, sunrise, sunset, camping, monsoon, weekend', max_length=300),
        ),
        migrations.AddField(
            model_name='destination',
            name='trekking_difficulty',
            field=models.CharField(choices=[('easy', 'Easy / Beginner'), ('moderate', 'Moderate'), ('difficult', 'Difficult / Challenging'), ('expert', 'Expert / Extreme'), ('none', 'Not Applicable')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='trip_duration_type',
            field=models.CharField(choices=[('half_day', 'Half Day (2-4 hrs)'), ('1_day', '1 Day Trip'), ('weekend', 'Weekend Getaway (2 Days)'), ('multi_day', 'Extended Multi-Day Trip')], db_index=True, default='1_day', max_length=20),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['trekking_difficulty'], name='destination_trekkin_545016_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['trip_duration_type'], name='destination_trip_du_e65271_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['ideal_season'], name='destination_ideal_s_fd723a_idx'),
        ),
    ]
