# Generated by Django 6.0.4 on 2026-08-18 11:10

import apps.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_published_alter_category_image_and_more'),
        ('cities', '0002_city_published_alter_city_banner_image_and_more'),
        ('destinations', '0006_destination_ideal_season_and_more'),
        ('states', '0002_state_image_state_latitude_state_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_history', models.TextField(help_text='Concise historical summary (1-2 paragraphs)')),
                ('detailed_history', models.TextField(help_text='Comprehensive historical narrative')),
                ('ancient_history', models.TextField(blank=True, help_text='Origins and Vedic / Ancient era background', null=True)),
                ('medieval_history', models.TextField(blank=True, help_text='Medieval dynasties, royal patrons, and invasions', null=True)),
                ('modern_history', models.TextField(blank=True, help_text='Colonial to post-independence evolution', null=True)),
                ('architecture', models.TextField(blank=True, help_text='Architectural style, layout, carvings, and engineering', null=True)),
                ('cultural_significance', models.TextField(blank=True, help_text='Festivals, traditions, rituals, and music', null=True)),
                ('religious_significance', models.TextField(blank=True, help_text='Puranic lore, sanctum details, and spiritual importance', null=True)),
                ('historical_events', models.JSONField(blank=True, default=list, help_text='List of key historical milestones')),
                ('important_dates', models.JSONField(blank=True, default=list, help_text="Timeline: [{'era': '...', 'year': '...', 'title': '...', 'description': '...'}]")),
                ('source_name', models.CharField(default='Archaeological Survey of India (ASI) / State Archaeology', max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=600, null=True)),
                ('verification_status', models.CharField(choices=[('verified', '100% Verified by Official Records'), ('needs_review', 'Needs Review'), ('outdated', 'Outdated Info')], default='verified', max_length=30)),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Destination Histories',
            },
        ),
        migrations.CreateModel(
            name='DestinationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('government', 'Government Tourism Department'), ('asi', 'Archaeological Survey of India (ASI)'), ('temple_trust', 'Official Temple Trust / Devasthanam'), ('unesco', 'UNESCO World Heritage Centre'), ('academic', 'Academic / Historical Research Archive'), ('verified_partner', 'Verified Travel Partner')], default='government', max_length=50)),
                ('source_url', models.URLField(blank=True, max_length=600, null=True)),
                ('license_info', models.CharField(default='Official Public Tourism Information / Fair Use Attribution', max_length=255)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-popularity_score', '-avg_rating', 'name']},
        ),
        migrations.AlterModelOptions(
            name='destinationvideo',
            options={'ordering': ['-is_primary', 'display_order', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='destination_name_96ccc3_idx',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='destination_publish_470086_idx',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='destination_feature_05c406_idx',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='destination_trendin_854c84_idx',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='destination_distric_a2708a_idx',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='destination_ideal_s_fd723a_idx',
        ),
        migrations.AddField(
            model_name='destination',
            name='ideal_duration',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 4:30', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Use as hero video background on detail page'),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='source',
            field=models.CharField(blank=True, default='Incredible India / Official Tourism', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='source_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='destinationvideo',
            name='video_type',
            field=models.CharField(choices=[('overview', 'Main Travel Video'), ('history', 'History & Heritage Documentary'), ('temple_tour', 'Temple & Spiritual Tour'), ('drone_cinematic', 'Drone & Cinematic Aerial'), ('guide', 'Travel Guide & Itinerary'), ('local_experience', 'Local Culture & Food Experience')], default='overview', max_length=50),
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_time_to_visit',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='budget_level',
            field=models.CharField(choices=[('low', 'Budget / Low'), ('medium', 'Moderate / Medium'), ('high', 'Luxury / High')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='closing_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='data_completeness_score',
            field=models.PositiveIntegerField(default=95, help_text='Percentage 0-100% based on data points present'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='destination',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Official Revenue District (e.g. Tirupati, Puri, Rudraprayag)', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='famous_for',
            field=models.CharField(blank=True, default='', help_text='One-liner: Why this place is internationally famous', max_length=300),
        ),
        migrations.AlterField(
            model_name='destination',
            name='is_hidden_gem',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='main_image',
            field=models.URLField(blank=True, default='', help_text='Direct verified CDN/Unsplash URL', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nearest_airport',
            field=models.CharField(blank=True, default='', help_text='Airport name + distance (e.g. Tirupati Airport (TIR) - 15 km)', max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nearest_bus_station',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nearest_railway',
            field=models.CharField(blank=True, default='', help_text='Railway station + distance (e.g. Tirupati Main (TPTY) - 2 km)', max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='opening_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='popularity_score',
            field=models.PositiveIntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='destination',
            name='recommended_duration',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.CharField(choices=[('south-india', 'South India'), ('north-india', 'North India'), ('west-india', 'West India'), ('east-india', 'East India'), ('central-india', 'Central India'), ('northeast-india', 'Northeast India')], db_index=True, default='south-india', max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='safety_info',
            field=models.TextField(blank=True, default='', help_text='Security guidelines, emergency contacts, local protocols'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='source_name',
            field=models.CharField(blank=True, default='Incredible India / Official State Tourism', max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='spiritual_tradition',
            field=models.CharField(blank=True, default='', help_text='Tradition (e.g. Vaishnavism, Shaivism, Shakta, Vajrayana)', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='suitable_for_tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated e.g. beginners, families, photography, camping', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='temple_architecture',
            field=models.CharField(blank=True, default='', help_text='Style (e.g. Dravidian, Nagara, Kalinga, Vesara)', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='temple_deity',
            field=models.CharField(blank=True, default='', help_text='Presiding Deity (e.g. Lord Venkateswara, Lord Shiva)', max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='things_to_do',
            field=models.TextField(blank=True, default='', help_text='Top experiences and activities'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='travel_style',
            field=models.CharField(choices=[('family', 'Family'), ('couple', 'Couple / Romantic'), ('solo', 'Solo Explorer'), ('adventure', 'Adventure'), ('spiritual', 'Spiritual'), ('nature', 'Nature'), ('historical', 'Historical'), ('cultural', 'Cultural'), ('beach', 'Beach'), ('wildlife', 'Wildlife')], db_index=True, default='cultural', max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='weather_info',
            field=models.TextField(blank=True, default='', help_text='Seasonal temperature and monsoon alerts'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/images/', validators=[apps.utils.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='destinationvideo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destinationvideo',
            name='video_url',
            field=models.URLField(help_text='Direct MP4 / CDN stream or embed URL', max_length=600),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['state', 'district'], name='destination_state_i_d058f7_idx'),
        ),
        migrations.AddField(
            model_name='destinationhistory',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='destinationsource',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='destinations.destination'),
        ),
        migrations.RemoveField(
            model_name='destination',
            name='airport_information',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='bus_information',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='culture_summary',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='history',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='how_to_reach',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='last_verified_at',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='local_transport',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='railway_information',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='travel_tips_summary',
        ),
    ]
