# Generated by Django 6.0.4 on 2026-08-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_activity_tag_alter_category_options_and_more'),
        ('destinations', '0007_destinationhistory_destinationsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='categories.activity'),
        ),
    ]
