# Generated by Django 6.0.4 on 2026-08-19 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_activity_tag_alter_category_options_and_more'),
        ('destinations', '0008_destination_activities'),
        ('regions', '0001_initial'),
        ('states', '0003_state_region_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='district_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='states.district'),
        ),
        migrations.AddField(
            model_name='destination',
            name='jyotirlinga_number',
            field=models.PositiveIntegerField(blank=True, help_text='Number 1 to 12 if part of 12 Jyotirlingas', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='region_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='regions.region'),
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='categories.tag'),
        ),
    ]
