# Generated by Django 6.0.4 on 2026-08-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_activity_tag_alter_category_options_and_more'),
        ('cities', '0003_city_district'),
        ('destinations', '0009_destination_district_obj_and_more'),
        ('regions', '0001_initial'),
        ('states', '0003_state_region_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created Destination'), ('UPDATED', 'Updated Details'), ('STATUS_CHANGE', 'Status Changed'), ('MEDIA_ADDED', 'Media Added'), ('IMPORTED', 'Imported via Pipeline')], default='UPDATED', max_length=50)),
                ('changed_by', models.CharField(default='System Administrator', max_length=150)),
                ('change_summary', models.TextField(blank=True, default='')),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='destination_trip_du_e65271_idx',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='destination_state_i_d058f7_idx',
        ),
        migrations.AddField(
            model_name='destination',
            name='content_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Admin Review'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived')], db_index=True, default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='source_type',
            field=models.CharField(blank=True, choices=[('tourism_board', 'Official Tourism Board'), ('government', 'Government Portal'), ('temple_trust', 'Temple / Religious Trust'), ('national_park', 'National Park Authority'), ('local_authority', 'Local Tourism Authority'), ('contributor', 'Original Contributor'), ('licensed', 'Licensed Source / Public Domain')], default='tourism_board', max_length=40),
        ),
        migrations.AddField(
            model_name='destination',
            name='source_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='license_info',
            field=models.CharField(blank=True, default='Public Domain / Licensed', max_length=200),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='photographer',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='source',
            field=models.CharField(blank=True, default='Official Tourism / Licensed', max_length=150),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='source_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['state'], name='destination_state_i_d7b51b_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['district'], name='destination_distric_a2708a_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['city'], name='destination_city_id_6c65b0_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['published'], name='destination_publish_470086_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['content_status'], name='destination_content_4b7244_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['featured'], name='destination_feature_05c406_idx'),
        ),
        migrations.AddField(
            model_name='destinationauditlog',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='destinations.destination'),
        ),
    ]
