# Generated by Django 6.0.4 on 2026-08-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_activity_tag_alter_category_options_and_more'),
        ('destinations', '0010_destinationauditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image', models.URLField(blank=True, default='', max_length=600)),
                ('featured', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='categories.category')),
                ('destinations', models.ManyToManyField(blank=True, related_name='travel_collections', to='destinations.destination')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
